/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socket;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mastery
 */
public class Game extends JFrame {
    
    //MY
    JButton  pecaAtual= new JButton();
    String tabuleiro[][] = { 
    {"V1", "V2","N","N","P1","P2" },
    {"V3", "V4","N","N","P3","P4" },
    {"V5", "V6","N","N","P5","P6" },
    {"V7", "V8","N","N","P7","P8" },
    {"V9", "V10","N","N","P9","P10" },
    {"V11", "V12","N","N","P11","P12" }
    };
    boolean vezDeJogar;
    boolean desitencia=false;
    int posX;
    int posY;
    String myTurn = "Sua vez!";
    String yourTurn = "Vez do outro jogador!";
    JButton pecaAtaque;
    JButton pecaAux;
    //variaveis
    Font fontText = new Font("Book Antiqua", Font.PLAIN, 30);
    Font fontButtons = new Font("Book Antiqua", Font.PLAIN, 18);

    private ServerSocket serverSocket = null;
    private Socket sockets = null;
    private ObjectInputStream entrada = null;
    private ObjectOutputStream saida = null;
    //jogo
    private String jogo[] = {"", "", "", "", "", "", "", "", ""};
    //server é o X e o cliente O
    private String xo = "";
    //nick1 o Server e o nick2 Cliente
    private String nick1, nick2, msg;
    //controle de fluxo
    private boolean sinal;
    private boolean pararSinal = true;


    public Game() {
        initComponents();
        setSize(525, 800);
        setResizable(false);
        setLocationRelativeTo(this);
        inicia();
        //criar evento para a janela
        addWindowListener(new WindowAdapter() {
            public void windowActivated(WindowEvent event) {
                try {
                    InetAddress thisIp = InetAddress.getLocalHost();
                    ip.setText(thisIp.getHostAddress());
                } catch (Exception e) {
                    ip.setText("127.0.0.1");
                }
            }

            @Override
            public void windowClosing(WindowEvent event) {
                if (sockets != null) {
                    enviarMensagem("Offline!");
                }
                encerrarTudo();
            }
        });

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ip = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        nick = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        desistir = new javax.swing.JButton();
        create = new javax.swing.JButton();
        join = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        V1 = new javax.swing.JButton();
        V2 = new javax.swing.JButton();
        V3 = new javax.swing.JButton();
        V4 = new javax.swing.JButton();
        V5 = new javax.swing.JButton();
        V6 = new javax.swing.JButton();
        V7 = new javax.swing.JButton();
        V8 = new javax.swing.JButton();
        V9 = new javax.swing.JButton();
        V10 = new javax.swing.JButton();
        V11 = new javax.swing.JButton();
        V12 = new javax.swing.JButton();
        P10 = new javax.swing.JButton();
        P11 = new javax.swing.JButton();
        P1 = new javax.swing.JButton();
        P3 = new javax.swing.JButton();
        P5 = new javax.swing.JButton();
        P7 = new javax.swing.JButton();
        P9 = new javax.swing.JButton();
        P12 = new javax.swing.JButton();
        P2 = new javax.swing.JButton();
        P4 = new javax.swing.JButton();
        P6 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        P8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        btn_esquerda = new javax.swing.JButton();
        btr_inferior = new javax.swing.JButton();
        btn_direita = new javax.swing.JButton();
        btn_superior = new javax.swing.JButton();
        cor = new javax.swing.JLabel();
        turn = new javax.swing.JLabel();
        Comer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sp = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        message = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ip.setBackground(new java.awt.Color(0, 0, 0));
        ip.setForeground(new java.awt.Color(0, 255, 0));
        ip.setText("jTextField1");
        getContentPane().add(ip);
        ip.setBounds(40, 20, 140, 30);

        port.setBackground(new java.awt.Color(0, 0, 0));
        port.setForeground(new java.awt.Color(51, 255, 0));
        port.setText("jTextField2");
        getContentPane().add(port);
        port.setBounds(230, 20, 70, 30);

        nick.setBackground(new java.awt.Color(0, 0, 0));
        nick.setForeground(new java.awt.Color(0, 255, 0));
        nick.setText("jTextField3");
        getContentPane().add(nick);
        nick.setBounds(340, 20, 140, 30);

        jLabel1.setBackground(new java.awt.Color(51, 255, 0));
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Nick:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 30, 30);

        jLabel2.setBackground(new java.awt.Color(51, 255, 0));
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("IP:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 14, 30);

        jLabel3.setBackground(new java.awt.Color(51, 255, 0));
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Porta:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 20, 40, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        desistir.setBackground(new java.awt.Color(0, 0, 0));
        desistir.setForeground(new java.awt.Color(0, 255, 0));
        desistir.setText("Desistir");
        desistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desistirActionPerformed(evt);
            }
        });
        jPanel1.add(desistir);
        desistir.setBounds(340, 60, 140, 30);

        create.setBackground(new java.awt.Color(0, 0, 0));
        create.setForeground(new java.awt.Color(0, 255, 0));
        create.setText("Criar");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create);
        create.setBounds(140, 60, 90, 30);

        join.setBackground(new java.awt.Color(0, 0, 0));
        join.setForeground(new java.awt.Color(0, 255, 0));
        join.setText("Entrar");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        jPanel1.add(join);
        join.setBounds(40, 60, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 100);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        V1.setBackground(new java.awt.Color(255, 0, 0));
        V1.setName("V1"); // NOI18N
        V1.setPreferredSize(new java.awt.Dimension(20, 20));
        V1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V1ActionPerformed(evt);
            }
        });
        jPanel3.add(V1);
        V1.setBounds(90, 40, 30, 30);

        V2.setBackground(new java.awt.Color(255, 0, 0));
        V2.setName("V2"); // NOI18N
        V2.setPreferredSize(new java.awt.Dimension(20, 20));
        V2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V2ActionPerformed(evt);
            }
        });
        jPanel3.add(V2);
        V2.setBounds(140, 40, 30, 30);

        V3.setBackground(new java.awt.Color(255, 0, 0));
        V3.setName("V3"); // NOI18N
        V3.setPreferredSize(new java.awt.Dimension(20, 20));
        V3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V3ActionPerformed(evt);
            }
        });
        jPanel3.add(V3);
        V3.setBounds(90, 90, 30, 30);

        V4.setBackground(new java.awt.Color(255, 0, 0));
        V4.setName("V4"); // NOI18N
        V4.setPreferredSize(new java.awt.Dimension(20, 20));
        V4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V4ActionPerformed(evt);
            }
        });
        jPanel3.add(V4);
        V4.setBounds(140, 90, 30, 30);

        V5.setBackground(new java.awt.Color(255, 0, 0));
        V5.setName("V5"); // NOI18N
        V5.setPreferredSize(new java.awt.Dimension(20, 20));
        V5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V5ActionPerformed(evt);
            }
        });
        jPanel3.add(V5);
        V5.setBounds(90, 140, 30, 30);

        V6.setBackground(new java.awt.Color(255, 0, 0));
        V6.setName("V6"); // NOI18N
        V6.setPreferredSize(new java.awt.Dimension(20, 20));
        V6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V6ActionPerformed(evt);
            }
        });
        jPanel3.add(V6);
        V6.setBounds(140, 140, 30, 30);

        V7.setBackground(new java.awt.Color(255, 0, 0));
        V7.setName("V7"); // NOI18N
        V7.setPreferredSize(new java.awt.Dimension(20, 20));
        V7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V7ActionPerformed(evt);
            }
        });
        jPanel3.add(V7);
        V7.setBounds(90, 190, 30, 30);

        V8.setBackground(new java.awt.Color(255, 0, 0));
        V8.setName("V8"); // NOI18N
        V8.setPreferredSize(new java.awt.Dimension(20, 20));
        V8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V8ActionPerformed(evt);
            }
        });
        jPanel3.add(V8);
        V8.setBounds(140, 190, 30, 30);

        V9.setBackground(new java.awt.Color(255, 0, 0));
        V9.setName("V9"); // NOI18N
        V9.setPreferredSize(new java.awt.Dimension(20, 20));
        V9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V9ActionPerformed(evt);
            }
        });
        jPanel3.add(V9);
        V9.setBounds(90, 240, 30, 30);

        V10.setBackground(new java.awt.Color(255, 0, 0));
        V10.setName("V10"); // NOI18N
        V10.setPreferredSize(new java.awt.Dimension(20, 20));
        V10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V10ActionPerformed(evt);
            }
        });
        jPanel3.add(V10);
        V10.setBounds(140, 240, 30, 30);

        V11.setBackground(new java.awt.Color(255, 0, 0));
        V11.setName("V11"); // NOI18N
        V11.setPreferredSize(new java.awt.Dimension(20, 20));
        V11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V11ActionPerformed(evt);
            }
        });
        jPanel3.add(V11);
        V11.setBounds(90, 290, 30, 30);

        V12.setBackground(new java.awt.Color(255, 0, 0));
        V12.setName("V12"); // NOI18N
        V12.setPreferredSize(new java.awt.Dimension(20, 20));
        V12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V12ActionPerformed(evt);
            }
        });
        jPanel3.add(V12);
        V12.setBounds(140, 290, 30, 30);

        P10.setBackground(new java.awt.Color(0, 0, 0));
        P10.setName("P10"); // NOI18N
        P10.setPreferredSize(new java.awt.Dimension(20, 20));
        P10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P10ActionPerformed(evt);
            }
        });
        jPanel3.add(P10);
        P10.setBounds(340, 240, 30, 30);

        P11.setBackground(new java.awt.Color(0, 0, 0));
        P11.setName("P11"); // NOI18N
        P11.setPreferredSize(new java.awt.Dimension(20, 20));
        P11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P11ActionPerformed(evt);
            }
        });
        jPanel3.add(P11);
        P11.setBounds(290, 290, 30, 30);

        P1.setBackground(new java.awt.Color(0, 0, 0));
        P1.setName("P1"); // NOI18N
        P1.setPreferredSize(new java.awt.Dimension(20, 20));
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });
        jPanel3.add(P1);
        P1.setBounds(290, 40, 30, 30);

        P3.setBackground(new java.awt.Color(0, 0, 0));
        P3.setName("P3"); // NOI18N
        P3.setPreferredSize(new java.awt.Dimension(20, 20));
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });
        jPanel3.add(P3);
        P3.setBounds(290, 90, 30, 30);

        P5.setBackground(new java.awt.Color(0, 0, 0));
        P5.setName("P5"); // NOI18N
        P5.setPreferredSize(new java.awt.Dimension(20, 20));
        P5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5ActionPerformed(evt);
            }
        });
        jPanel3.add(P5);
        P5.setBounds(290, 140, 30, 30);

        P7.setBackground(new java.awt.Color(0, 0, 0));
        P7.setName("P7"); // NOI18N
        P7.setPreferredSize(new java.awt.Dimension(20, 20));
        P7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P7ActionPerformed(evt);
            }
        });
        jPanel3.add(P7);
        P7.setBounds(290, 190, 30, 30);

        P9.setBackground(new java.awt.Color(0, 0, 0));
        P9.setName("P9"); // NOI18N
        P9.setPreferredSize(new java.awt.Dimension(20, 20));
        P9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P9ActionPerformed(evt);
            }
        });
        jPanel3.add(P9);
        P9.setBounds(290, 240, 30, 30);

        P12.setBackground(new java.awt.Color(0, 0, 0));
        P12.setName("P12"); // NOI18N
        P12.setPreferredSize(new java.awt.Dimension(20, 20));
        P12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P12ActionPerformed(evt);
            }
        });
        jPanel3.add(P12);
        P12.setBounds(340, 290, 30, 30);

        P2.setBackground(new java.awt.Color(0, 0, 0));
        P2.setName("P2"); // NOI18N
        P2.setPreferredSize(new java.awt.Dimension(20, 20));
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });
        jPanel3.add(P2);
        P2.setBounds(340, 40, 30, 30);

        P4.setBackground(new java.awt.Color(0, 0, 0));
        P4.setName("P4"); // NOI18N
        P4.setPreferredSize(new java.awt.Dimension(20, 20));
        P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ActionPerformed(evt);
            }
        });
        jPanel3.add(P4);
        P4.setBounds(340, 90, 30, 30);

        P6.setBackground(new java.awt.Color(0, 0, 0));
        P6.setName("P6"); // NOI18N
        P6.setPreferredSize(new java.awt.Dimension(20, 20));
        P6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P6ActionPerformed(evt);
            }
        });
        jPanel3.add(P6);
        P6.setBounds(340, 140, 30, 30);

        jButton24.setBackground(new java.awt.Color(0, 0, 0));
        jButton24.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton24);
        jButton24.setBounds(340, 140, 30, 30);

        P8.setBackground(new java.awt.Color(0, 0, 0));
        P8.setName("P8"); // NOI18N
        P8.setPreferredSize(new java.awt.Dimension(20, 20));
        P8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P8ActionPerformed(evt);
            }
        });
        jPanel3.add(P8);
        P8.setBounds(340, 190, 30, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(100, 250, 250, 20);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(100, 100, 250, 10);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(100, 55, 250, 10);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(100, 150, 250, 10);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(100, 200, 250, 20);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(100, 300, 250, 20);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(300, 60, 10, 240);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator8);
        jSeparator8.setBounds(350, 60, 10, 240);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setMinimumSize(new java.awt.Dimension(10, 250));
        jPanel3.add(jSeparator9);
        jSeparator9.setBounds(100, 60, 10, 240);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator10);
        jSeparator10.setBounds(150, 60, 10, 240);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator11);
        jSeparator11.setBounds(200, 60, 10, 240);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator12);
        jSeparator12.setBounds(250, 60, 10, 240);

        btn_esquerda.setText("Esquerda");
        btn_esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esquerdaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_esquerda);
        btn_esquerda.setBounds(19, 370, 100, 23);

        btr_inferior.setText("Diagonal Inferior");
        btr_inferior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btr_inferiorActionPerformed(evt);
            }
        });
        jPanel3.add(btr_inferior);
        btr_inferior.setBounds(140, 390, 150, 23);

        btn_direita.setText("Direita ");
        btn_direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_direitaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_direita);
        btn_direita.setBounds(310, 370, 100, 23);

        btn_superior.setText("Diagonal Superior");
        btn_superior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_superiorActionPerformed(evt);
            }
        });
        jPanel3.add(btn_superior);
        btn_superior.setBounds(140, 340, 150, 23);

        cor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cor.setText("Sua cor:");
        jPanel3.add(cor);
        cor.setBounds(40, 10, 190, 20);

        turn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        turn.setText("vez:");
        jPanel3.add(turn);
        turn.setBounds(290, 10, 190, 20);

        Comer.setText("Comer");
        Comer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComerActionPerformed(evt);
            }
        });
        jPanel3.add(Comer);
        Comer.setBounds(410, 140, 90, 80);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 520, 430);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(51, 255, 0));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        sp.setViewportView(textArea);

        jPanel2.add(sp);
        sp.setBounds(20, 30, 470, 96);

        message.setBackground(new java.awt.Color(0, 0, 0));
        message.setForeground(new java.awt.Color(51, 255, 0));
        message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageKeyPressed(evt);
            }
        });
        jPanel2.add(message);
        message.setBounds(20, 150, 470, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 530, 520, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getPositionButton(JButton peca){
        for(int i=0; i<6; i++){
            for(int j=0; j<6; j++){
                if((peca.getName()).equals(tabuleiro[i][j])){
                   posX = i;
                   posY = j;
                   break;
                }
            }
        }
    }
    private void printTabuleiro(){
        for(int i=0; i<6; i++){
            for(int j=0; j<6; j++){
                System.out.print(tabuleiro[i][j]+" ");
            }
            System.out.print("\n");
        }
    }
     private void updateTabuleiro(int i, int j){
         getPositionButton(pecaAtual);
         tabuleiro[posX][posY] ="N";
         tabuleiro[i][j] = pecaAtual.getName();
     }
    
    private void updateTabuleiro(String acao, String color){
        //String color = cor.getText();
        getPositionButton(pecaAtual);
        if(acao.equals("ataque")){ 
            tabuleiro[posX][posY] ="N";
            getPositionButton(pecaAux);
            tabuleiro[posX][posY] = pecaAtual.getName();
        }
        if(color.contains("Vermelho")){
            System.out.println("Modificando vermelhas");
            if(acao.equals("direita")){
                tabuleiro[posX][posY+1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
                System.out.println("direitas");
            }else if (acao.equals("superior")){
                tabuleiro[posX-1][posY+1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
            }else if (acao.equals("inferior")){
                tabuleiro[posX+1][posY+1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
            }
        }else{
            if(acao.equals("esquerda")){
                tabuleiro[posX][posY-1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
            }else if (acao.equals("superior")){
                tabuleiro[posX-1][posY-1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
            }else if (acao.equals("inferior")){
                tabuleiro[posX+1][posY-1] = pecaAtual.getName();
                tabuleiro[posX][posY] ="N";
            }
        }
        printTabuleiro();
  
    }
    
    //verfica movimento e atualiza tabuleiro 
    /*private boolean verifyMoviment(String moviment){
        printTabuleiro();
        getPositionButton();
        if(moviment.equals("direita")){
            try{
                System.out.println("AAA: " + tabuleiro[posX][posY+1]);
                String nextPos = tabuleiro[posX][posY+1]; 
                if(nextPos.contains("N")){
                    System.out.println("Movimento válido");
                    tabuleiro[posX][posY+1] = pecaAtual.getName();
                    tabuleiro[posX][posY] ="N";
                    return true;
                }else{
                    System.out.println("Movimento inválido");
                    return false;
                }
            }catch(Exception e){
                System.out.println("Movimento inválido");
                return false;
            }
        }
        return false;
    }*/
    
    //seta posição e envia movimento
    private void setPositionButton(int x, int y, String acao){
        
        System.out.println(" Enviando Antes Peça: " +pecaAtual.getName()+" " +pecaAtual.getX()+ " "+pecaAtual.getY() );
        pecaAtual.setLocation(pecaAtual.getX() + x,pecaAtual.getY()+ y);
        enviarMensagem(pecaAtual.getName()+" "+acao);
        updateTabuleiro(acao,cor.getText());
        System.out.println("Enviando Depois Peça: " +pecaAtual.getName()+" " +pecaAtual.getX()+ " "+pecaAtual.getY() );
        printTabuleiro();
    }
    //seta posiçãao
    private void setPositionButton(int x, int y){
        System.out.println(" Antes Peça: " +pecaAtual.getName()+" " +pecaAtual.getX()+ " "+pecaAtual.getY() );
        pecaAtual.setLocation(pecaAtual.getX() + x,pecaAtual.getY()+ y);
        System.out.println("Depois Peça: " +pecaAtual.getName()+" " +pecaAtual.getX()+ " "+pecaAtual.getY() );
    }
    
    private void updateTurn(){
        if(vezDeJogar){
            turn.setText(myTurn);
        }else{
            turn.setText(yourTurn);
        }
    }
    private void desistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desistirActionPerformed

        JOptionPane.showMessageDialog(null, "Você desistiu!");
        enviarMensagem("Desistindo!"); // send request to client, for new game
    }//GEN-LAST:event_desistirActionPerformed

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        try {
            if (nick.getText().equals("") || nick.getText().equals(" ")) {
                try {
                    JOptionPane.showMessageDialog(null, "Você nao colocou seu nick!");
                } catch (ExceptionInInitializerError exc) {
                }
                return;
            }
            cor.setText("Sua cor: Preto");
            vezDeJogar = false;
            updateTurn();
            sockets = new Socket(ip.getText(), Integer.parseInt(port.getText()));

            saida = new ObjectOutputStream(sockets.getOutputStream());
            saida.flush();
            entrada = new ObjectInputStream(sockets.getInputStream());

            msg = (String) entrada.readObject();
            textArea.append(msg + "\n");
            ScrollToBottom();

            nick2 = nick.getText();

            msg = (String) entrada.readObject(); // get nick from host
            nick1 = "" + msg;

            enviarMensagem(nick2);

            //estadoButton(true);
            message.setEditable(true);

            ip.setEnabled(false);
            port.setEnabled(false);
            nick.setEnabled(false);

            textArea.append("Vermelho joga primeiro!\n");
            ScrollToBottom();
            //Desabilitando menu superior
            join.setEnabled(false);
            create.setEnabled(false);
            ip.setEnabled(false);
            port.setEnabled(false);
            nick.setEnabled(false);

            new Game.recebeMensagem("Recebe"); // thread for receive data from host		
        } catch (Exception e) {
            encerrarTudo();
            executarTudo();
            try {
                JOptionPane.showMessageDialog(null, "Erro server esta offline: \n" + e);
            } catch (ExceptionInInitializerError exc) {
            }
        }

    }//GEN-LAST:event_joinActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if (nick.getText().equals("") || nick.getText().equals(" ")) {
            try {
                JOptionPane.showMessageDialog(null, "Você nao colocou seu nick!");
            } catch (ExceptionInInitializerError exc) {
            }
            return;
        }

        new Game.criarThread("CreateButton"); // we need thread while we wait for client, because we don't want frozen frame

    }//GEN-LAST:event_createActionPerformed

    private void messageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textArea.append(nick.getText() + ":" + message.getText() + "\n");
            ScrollToBottom();
            enviarMensagem(message.getText());
            message.setText(" ");
        }
    }//GEN-LAST:event_messageKeyPressed

    private void P10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P10ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P10;
    }//GEN-LAST:event_P10ActionPerformed

    private void P11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P11ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P11;
    }//GEN-LAST:event_P11ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P1;
    }//GEN-LAST:event_P1ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P3;
    }//GEN-LAST:event_P3ActionPerformed

    private void P5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P5;
    }//GEN-LAST:event_P5ActionPerformed

    private void P7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P7ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P7;
    }//GEN-LAST:event_P7ActionPerformed

    private void P9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P9ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P9;
    }//GEN-LAST:event_P9ActionPerformed

    private void P12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P12ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P12;
    }//GEN-LAST:event_P12ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P2;
    }//GEN-LAST:event_P2ActionPerformed

    private void P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P4;
    }//GEN-LAST:event_P4ActionPerformed

    private void P6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P6ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P6;
    }//GEN-LAST:event_P6ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P7;
    }//GEN-LAST:event_jButton24ActionPerformed

    private void P8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P8ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = P8;
    }//GEN-LAST:event_P8ActionPerformed

    private void btn_esquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esquerdaActionPerformed
        if(vezDeJogar){
            String btncor = cor.getText();
            if(!btncor.contains("Vermelho") && pecaAtual.getName().contains("P")){
                setPositionButton(-50,0,"esquerda"); 
                vezDeJogar = false;
                updateTurn();
            }
            
        }
        
    }//GEN-LAST:event_btn_esquerdaActionPerformed

    private void btr_inferiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btr_inferiorActionPerformed
        if(vezDeJogar){
             String btncor = cor.getText();
            if(btncor.contains("Vermelho") && pecaAtual.getName().contains("V")){
                setPositionButton(50,50,"inferior");
                vezDeJogar = false;
                updateTurn();
            }else if(btncor.contains("Preto") && pecaAtual.getName().contains("P")){
                setPositionButton(-50,50,"inferior");
                vezDeJogar = false;
                updateTurn();
            }   
           
        }
       
    }//GEN-LAST:event_btr_inferiorActionPerformed

    private void btn_direitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_direitaActionPerformed
        if(vezDeJogar){
            String btncor = cor.getText();
            if(!btncor.contains("Preto") && pecaAtual.getName().contains("V")){
                setPositionButton(50,0,"direita"); 
                vezDeJogar = false;
                updateTurn();
            }
        }
        
    }//GEN-LAST:event_btn_direitaActionPerformed

    private void btn_superiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_superiorActionPerformed
       if(vezDeJogar){  
            String btncor = cor.getText();
            if(btncor.contains("Vermelho")&& pecaAtual.getName().contains("V")){
                setPositionButton(50,-50,"superior");  
                vezDeJogar = false;
                updateTurn();
            }if(btncor.contains("Preto") && pecaAtual.getName().contains("P")){
                setPositionButton(-50,-50,"superior");  
                vezDeJogar = false;
                updateTurn();
            }
       }
        
    }//GEN-LAST:event_btn_superiorActionPerformed

    private void V1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V1ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V1;
    }//GEN-LAST:event_V1ActionPerformed

    private void V2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V2ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V2;
    }//GEN-LAST:event_V2ActionPerformed

    private void V3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V3ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V3;
    }//GEN-LAST:event_V3ActionPerformed

    private void V4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V4ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V4;
    }//GEN-LAST:event_V4ActionPerformed

    private void V5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V5ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V5;
    }//GEN-LAST:event_V5ActionPerformed

    private void V6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V6ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V6;
    }//GEN-LAST:event_V6ActionPerformed

    private void V7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V7ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V7;
    }//GEN-LAST:event_V7ActionPerformed

    private void V8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V8ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V8;
    }//GEN-LAST:event_V8ActionPerformed

    private void V9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V9ActionPerformed
       pecaAtaque = pecaAtual;
       pecaAtual = V9;
    }//GEN-LAST:event_V9ActionPerformed

    private void V10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V10ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V10;
    }//GEN-LAST:event_V10ActionPerformed

    private void V11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V11ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V11;
    }//GEN-LAST:event_V11ActionPerformed

    private void V12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V12ActionPerformed
        pecaAtaque = pecaAtual;
        pecaAtual = V12;
    }//GEN-LAST:event_V12ActionPerformed

    private void ComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComerActionPerformed
        int x;
        int y;
        if(vezDeJogar){
            System.out.println("Peça ataque:"+pecaAtaque.getName()+" Peça atual:"+pecaAtual.getName());
            OcultaPeca(pecaAtual);
            x = pecaAtual.getX() - pecaAtaque.getX();
            y = pecaAtual.getY() - pecaAtaque.getY();;
            pecaAux = pecaAtual;
            pecaAtual = pecaAtaque;
            getPositionButton(pecaAux);
            setPositionButton(x,y,"ataque "+pecaAux.getX()+" "+pecaAux.getY()+" "+posX+" "+posY+" "+pecaAux.getName());  
            vezDeJogar = false;
            updateTurn();
            pecaAux.setLocation(50,50);
        }
        
    }//GEN-LAST:event_ComerActionPerformed
    
    private void OcultaPeca(JButton button){
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    //funções
    public void inicia() {
        port.setText("5000");
        nick.setText("");
        textArea.setEditable(false);
    }
   
    // --- CREATE BUTTON THREAD ---

    private class criarThread implements Runnable {

        public criarThread(String name) {
            new Thread(this, name).start();
        }
        public void run() {
            try {
                join.setEnabled(false);
                create.setEnabled(false);
                port.setEnabled(false);
                nick.setEnabled(false);

                serverSocket = new ServerSocket(Integer.parseInt(port.getText()));
                
                textArea.append("Esperando cliente...\n");
                cor.setText("Sua cor: Vermelho");
                
                vezDeJogar = true;
                updateTurn();
                ScrollToBottom();
                sockets = serverSocket.accept();

                saida = new ObjectOutputStream(sockets.getOutputStream());
                saida.flush();
                entrada = new ObjectInputStream(sockets.getInputStream());
                enviarMensagem(nick.getText() + ": conectado com sucesso!");
                textArea.append("Cliente conectado com sucesso!\n");
                ScrollToBottom();            

                nick1 = nick.getText();

                enviarMensagem(nick1);

                msg = (String) entrada.readObject(); 
                nick2 = "" + msg;

                
                message.setEditable(true);
                ip.setEnabled(false);

                textArea.append("Vermelho joga primeiro!\n");
                
                
                ScrollToBottom();
                new recebeMensagem("recebeData");
            } catch (Exception e) {
                encerrarTudo();
                executarTudo();
                try {
                    JOptionPane.showMessageDialog(null, "Erro ao criar o jogo:\n" + e);
                } catch (ExceptionInInitializerError exc) {
                }
            }
        }
    }
    
    // --- envia mensagens ---
    private void enviarMensagem(String p) {
        try {
            if (pararSinal) {
                System.err.println(p);
                saida.writeObject(p);
                saida.flush();
            }
        } catch (SocketException e) {
            if (pararSinal) {
                pararSinal = false;
                encerrarTudo();
                executarTudo();
            }
        } catch (Exception e) {
            if (pararSinal) {
                pararSinal = false;
                encerrarTudo();
                executarTudo();
                try {
                    JOptionPane.showMessageDialog(null, "Fluxo de dados desconectado:\n" + e);
                } catch (ExceptionInInitializerError exc) {
                }
            }
        }
    }
    
    private JButton getbutton(String name){
        JButton  pecas[] = {V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12 };
        
        for(int i=0; i<23;i++){
            System.out.println("Print: "+pecas[i].getName());
            if(pecas[i].getName().equals(name)){
                System.out.println("achei a pecça");
                return pecas[i];
            }
        }
        return V1;
    }
    // --- recebe messages com thread ---
    private class recebeMensagem implements Runnable {

        private boolean auxsinal;
        private String rmsg;

        public recebeMensagem(String i) {
            auxsinal = true;
            rmsg = i;
            new Thread(this, rmsg).start();
        }

        public void run() {
            //primeiro player controla vermelhas
            //segundo player controla pretas
            
            while (auxsinal) {
                try {
                    msg = "";
                    msg = (String) entrada.readObject();
                    System.out.println("Recebendo");
                    System.out.println(msg);
                    System.out.println(rmsg);
                    if (rmsg.equals("Recebe")) // client recebe dados do host/server
                    {   
                        
                        if (msg.contains("V10")){
                            pecaAtual = V10; 
                        }else if (msg.contains("V11")){
                            pecaAtual = V11; 
                        }else if (msg.contains("V12")){
                            pecaAtual = V12;   
                        }else if (msg.contains("V1")){
                            pecaAtual = V1;
                        }else if (msg.contains("V1")){
                            pecaAtual = V1; 
                        }else if (msg.contains("V2")){
                            pecaAtual = V2;
                        }else if (msg.contains("V3")){
                            pecaAtual = V3;
                        }else if (msg.contains("V4")){
                            pecaAtual = V4;
                        }else if (msg.contains("V5")){
                            pecaAtual = V5;
                        }else if (msg.contains("V6")){
                            pecaAtual = V6;
                        }else if (msg.contains("V7")){
                            pecaAtual = V7; 
                        }else if (msg.contains("V8")){
                            pecaAtual = V8; 
                        }else if (msg.contains("V9")){
                            pecaAtual = V9;
                        }else {
                            textArea.append(nick1 + ":" + msg + "\n");
                            ScrollToBottom();
                        }
                        String updateColor = "Vermelho";
                        //setando jogada
                        if(msg.contains("direita")){
                              setPositionButton(50,0);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("direita",updateColor);
                        }else if(msg.contains("inferior")){
                            setPositionButton(50,50);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("inferior",updateColor);
                        }else if(msg.contains("superior")){
                            setPositionButton(50,-50);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("superior",updateColor);
                        }else if(msg.contains("ataque")){
                            String array[] = new String[7];
                            array = msg.split(" ");
                            setPositionButton( Integer.parseInt(array[2])- pecaAtual.getX(), Integer.parseInt(array[3])-pecaAtual.getY());
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro(Integer.parseInt(array[4]),Integer.parseInt(array[5]));
                            JButton button = getbutton(array[6]);
                            OcultaPeca(button);
                            button.setLocation(50,50);
                        }
                        
                        //verificando desistencia
                        if(msg.equals("Desistindo!")){
                           JOptionPane.showMessageDialog(null, "Parabéns, seu adversário desistiu!");
                           desitencia = true;
                           encerrarTudo();
                           
                        }
                        pecaAtual=new JButton();
              
                    } else if (rmsg.equals("recebeData")) // host/server recebe dados do client
                    {   
                        
                        if (msg.contains("P10")){
                            pecaAtual = P10; 
                        }else if (msg.contains("P11")){
                            pecaAtual = P11; 
                        }else if (msg.contains("P12")){
                            pecaAtual = P12;
                        }else if (msg.contains("P1")){
                            pecaAtual = P1;
                        }else if (msg.contains("P2")){
                            pecaAtual = P2; 
                        }else if (msg.contains("P2")){
                            pecaAtual = P2;
                        }else if (msg.contains("P3")){
                            pecaAtual = P3;
                        }else if (msg.contains("P4")){
                            pecaAtual = P4;
                        }else if (msg.contains("P5")){
                            pecaAtual = P5;
                        }else if (msg.contains("P6")){
                            pecaAtual = P6;
                        }else if (msg.contains("P7")){
                            pecaAtual = P7; 
                        }else if (msg.contains("P8")){
                            pecaAtual = P8; 
                        }else if (msg.contains("P9")){
                            pecaAtual = P9;
                        }else {
                            textArea.append(nick2 + ":" + msg + "\n");
                            ScrollToBottom();
                        }
                        
                        String updateColor = "Preto";
                        //setando jogada
                        if(msg.contains("esquerda")){
                            setPositionButton(-50,0);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("esquerda",updateColor);
                        }else if(msg.contains("inferior")){
                            setPositionButton(-50,50);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("inferior",updateColor);
                        }else if(msg.contains("superior")){
                            setPositionButton(-50,-50);
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro("superior",updateColor);
                        }else if(msg.contains("ataque")){
                            String array[] = new String[7];
                            array = msg.split(" ");
                            setPositionButton( Integer.parseInt(array[2])- pecaAtual.getX(), Integer.parseInt(array[3])-pecaAtual.getY());
                            vezDeJogar = !vezDeJogar;
                            updateTurn();
                            updateTabuleiro(Integer.parseInt(array[4]),Integer.parseInt(array[5]));
                            JButton button = getbutton(array[6]);
                            OcultaPeca(button);
                            button.setLocation(50, 50);
                        }
                        
                        if(msg.equals("Desistindo!")){
                            JOptionPane.showMessageDialog(null, "Parabéns, seu adversário desistiu!");
                            desitencia = true;
                            encerrarTudo();
                        }
                        pecaAtual=new JButton();
                        
                    }
                } catch (Exception e) {
                    auxsinal = false;
                    encerrarTudo();
                    //executarTudo();
                    try {
                        if(!desitencia){
                             JOptionPane.showMessageDialog(null, "Parabéns! Seu adversário desistiu!");
                        }
                       
                    } catch (ExceptionInInitializerError exc) {
                    }
                }
            }
        }
    }

    // --- restart estado inicial ---
    private void executarTudo() {
        //buttonDefault();
        //estadoButton(false);

        msg = "";
        
        ip.setEnabled(true);
        port.setEnabled(true);
        nick.setEnabled(true);
        create.setEnabled(true);
        join.setEnabled(true);

        desistir.setEnabled(false);
        message.setEditable(false);
    }

    // ---fecha todos fluxos ---
    private void encerrarTudo() {
        try {
            saida.flush();
        } catch (Exception e) {
        }
        try {
            saida.close();
        } catch (Exception e) {
        }
        try {
            entrada.close();
        } catch (Exception e) {
        }
        try {
            serverSocket.close();
        } catch (Exception e) {
        }
        try {
            sockets.close();
        } catch (Exception e) {
        }
    }

    // --- acompanha o chat ---
    public void ScrollToBottom() {
        textArea.setCaretPosition(textArea.getText().length());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comer;
    private javax.swing.JButton P1;
    private javax.swing.JButton P10;
    private javax.swing.JButton P11;
    private javax.swing.JButton P12;
    private javax.swing.JButton P2;
    private javax.swing.JButton P3;
    private javax.swing.JButton P4;
    private javax.swing.JButton P5;
    private javax.swing.JButton P6;
    private javax.swing.JButton P7;
    private javax.swing.JButton P8;
    private javax.swing.JButton P9;
    private javax.swing.JButton V1;
    private javax.swing.JButton V10;
    private javax.swing.JButton V11;
    private javax.swing.JButton V12;
    private javax.swing.JButton V2;
    private javax.swing.JButton V3;
    javax.swing.JButton V4;
    private javax.swing.JButton V5;
    private javax.swing.JButton V6;
    private javax.swing.JButton V7;
    private javax.swing.JButton V8;
    private javax.swing.JButton V9;
    private javax.swing.JButton btn_direita;
    private javax.swing.JButton btn_esquerda;
    private javax.swing.JButton btn_superior;
    private javax.swing.JButton btr_inferior;
    private javax.swing.JLabel cor;
    private javax.swing.JButton create;
    private javax.swing.JButton desistir;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton join;
    private javax.swing.JTextField message;
    private javax.swing.JTextField nick;
    private javax.swing.JTextField port;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel turn;
    // End of variables declaration//GEN-END:variables
}
